### ISSUE TITLE
请求与贵镜像站元信息相关的协助

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [PKUOSC/issues#1]
在项目 [mirrorz](https://github.com/tuna/mirrorz) 中存放着描述贵镜像站的[元信息](https://github.com/tuna/mirrorz/blob/master/static/json/site/pku.json)，可能有不准确的地方，需要一定的修正。

特别注意到，在 mirrorz 暗色模式下，贵站的 logo 展示效果较为不佳，可以提供一个 `logo_darkmode` 域。

另外也可以新增例如 `request` （镜像请求）`big`（测速文件） 等域，这些域的详细说明在[README](https://github.com/tuna/mirrorz/blob/master/README.md)中。

**Comment by JeremyGuo** [comment]
Dark mode 的 logo 已经添加并提交pull request，其他功能（摸头），这几天慢慢搞
