### ISSUE TITLE
A typo in the CTAN mirror help

### ISSUE THREAD

**Issue by thezzisu** [PKUOSC/issues#14]
The CTAN mirror help says, use the following command to change the source:
```
tlmgr option repository https://mirrors.pku.edu.cn/CTAN/systems/texlive/tlnet
```
However, the actually usable URL is `https://mirrors.pku.edu.cn/ctan/systems/texlive/tlnet`, which has a lowercase `ctan` in url pathname.

<img width="1902" alt="image" src="https://user-images.githubusercontent.com/21094314/187136887-e161a800-546b-4bc6-9492-e64da8b41aa9.png">
Get `https://mirrors.pku.edu.cn/CTAN/systems/texlive/tlnet/update-tlmgr-latest.sh` returned the PKU mirror SPA frontend instead of the actual file content.

**Comment by fuzhenxin** [comment]
Help document is updated. Thanks!

**Comment by thezzisu** [comment]
Thank you ;D
