### ISSUE TITLE
Archlinux cannot download python-tomlkit

### ISSUE THREAD

**Issue by Firestar-Reimu** [PKUOSC/issues#16]
```
error: failed retrieving file 'python-tomlkit-0.11.4-1-any.pkg.tar.zst' from mirrors.pku.edu.cn : The requested URL returned error: 404
```

**Comment by fuzhenxin** [comment]
This package is not found in other mirros for archlniux. After searching the package name, it only appears in artix linux repos. Any method to reproduce the error?

**Comment by Firestar-Reimu** [comment]
This happens when I download spyder

I can correctly install it from opentuna.cn

PS: too many typos

**Comment by fuzhenxin** [comment]
你的安装命令是否含有-y参数，python-tomlkit已经在archlinux仓库更新为新版，未同步仓库会导致安装失败。我安装spyder未出错，默认使用新版tomlkit。

**Comment by Firestar-Reimu** [comment]
我的安装命令确实没有-y参数，直接用的`sudo pacman -S`
