### ISSUE TITLE
Debian缺少使用文档

### ISSUE THREAD

**Issue by fuzhenxin** [PKUOSC/issues#19]
https://github.com/PKUOSC/Mirror-doc

**Comment by ouyen** [comment]
补了, 但是没有完全补, 在Help页面添加了, 但是Mirrors页面没有对应的link
<img width="173" alt="image" src="https://user-images.githubusercontent.com/60745334/219872842-13a1a808-320c-4913-bc71-b4a6c70c8eda.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/60745334/219872866-4f1b5e3b-aa0d-4246-b13f-f57f921506d2.png">

**Comment by fuzhenxin** [comment]
已修复，感谢提醒
