### ISSUE TITLE
请求开放同步状态数据的跨域访问

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [PKUOSC/issues#2]
同步状态数据的 url 是 https://mirrors.pku.edu.cn/monitor/status ，该数据也可用于其他项目（例如 [mirrorz](https://mirrorz.org)），故请求开放其跨域访问，或者几个特定站的跨域访问。

具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

另：注意到贵站的其余状态数据（流量，磁盘占用等）已经开放跨域访问，这些数据可能被其他项目（包括 mirrorz）使用。

**Comment by ZenithalHourlyRate** [comment]
> 具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`

我们建立了一个新的站点 https://mirrors.cngi.edu.cn ，故请求加上 mirrors.cngi.edu.cn 和 mirrors.edu.cn （预期中可以拿到）的 CORS

与此同时，我们也开始提供跳转服务，可以参考 https://mirrors.cngi.edu.cn/ubuntu?trace ，这需要提供一个 [mirrorz.d.json](https://github.com/mirrorz-org/mirrorz-302#mirrorzdjson)

**Comment by JeremyGuo** [comment]
镜像站最近还有别的改动，10月前会搞定

**Comment by ZenithalHourlyRate** [comment]
Any update?

**Comment by JeremyGuo** [comment]
We will update our website this week.

**Comment by ZenithalHourlyRate** [comment]
> > 具体方法为添加 `Access-Control-Allow-Origin: *` 的头或者（在`referer: https://mirrorz.org/`时）添加 `Access-Control-Allow-Origin: https://mirrorz.org`
> 
> 我们建立了一个新的站点 https://mirrors.cngi.edu.cn ，故请求加上 mirrors.cngi.edu.cn 和 mirrors.edu.cn （预期中可以拿到）的 CORS

我们拿到了 mirrors.cernet.edu.cn，也需要对该站点加上 CORS

> 
> 与此同时，我们也开始提供跳转服务，可以参考 https://mirrors.cngi.edu.cn/ubuntu?trace ，这需要提供一个 [mirrorz.d.json](https://github.com/mirrorz-org/mirrorz-302#mirrorzdjson)

**Comment by fuzhenxin** [comment]
已增加 mirrors.cngi.edu.cn和 mirrors.cernet.edu.cn！

**Comment by ZenithalHourlyRate** [comment]
> 已增加 mirrors.cngi.edu.cn和 mirrors.cernet.edu.cn！

非常感谢！

同时，我们注意到 PKU 这边的磁盘数据是通过 https://mirrors.pku.edu.cn/monitor_device_status/disk_space.json 提供的，这更改了 API（旧 API 在[此](https://github.com/mirrorz-org/mirrorz-parser/commit/5035a9f12425ae858858f845c1e56f13b18b9771)），可以对这个 json 开放三个站点的 CORS 吗

另外，mirrors.cernet.edu.cn 的一大特色在于提供跳转服务，我们恳切邀请贵站提供 mirrorz.d.json，详细格式可以在 https://github.com/mirrorz-org/mirrorz-302#mirrorzdjson 获取，样例可以在 https://github.com/mirrorz-org/mirrorz-d-extension 找到。简单来说，贵站提供贵校的出口 IP 段和 CERNET ASN，做成一个 json，通过网站提供或直接放在 mirrorz-d-extension 文件夹中，即可支持该服务。感谢贵站的支持！

**Comment by fuzhenxin** [comment]
您好！磁盘数据的CORS由于之前一次更新误删了，现在加回来了！
mirrorz.d.json我们尽快体提供，感谢！
