### ISSUE TITLE
树莓派源不完整

### ISSUE THREAD

**Issue by AnterCreeper** [PKUOSC/issues#23]
除了raspbian, 还有树莓派基金会的源，提供系统内核，驱动，以及一些工具
在/etc/apt/sources.list.d/raspi.list下
上游地址：http://archive.raspberrypi.org/debian/ buster main ui

**Comment by fuzhenxin** [comment]
已增加：https://mirrors.pku.edu.cn/raspberrypi/

**Comment by AnterCreeper** [comment]
thx!
