### ISSUE TITLE
希望增加ImmortalWrt和OPNsense镜像

### ISSUE THREAD

**Issue by troubadour-hell** [PKUOSC/issues#24]
最近对计算机网络产生了兴趣，接触了一些路由器和防火墙系统，很高兴发现学校的镜像站已经有了OpenWrt镜像。能否再增加下ImmortalWrt和OPNsense的镜像？ImmortalWrt是OpenWrt的一个分支，有着优秀的开发者、高质量的代码和广泛的用户群体。OPNsense是基于FreeBSD的防火墙，具有良好的性能、强大的功能和稳定性。希望能在学校的镜像站上看到它们，方便对网络感兴趣的同学研究、使用。

ImmortalWrt项目地址：https://github.com/immortalwrt/immortalwrt
同步方式：RSYNC_PASSWORD="immortalwrt-org" rsync -ahvHP --delete "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" “$TARGET_DIR”

OPNsense项目地址：https://github.com/opnsense
同步方式：rsync -vaz "rsync://mirror.wdc1.us.leaseweb.net/opnsense" "$TARGET_DIR"

**Comment by bradfordzhang** [comment]
支持！很好的建议 :)

**Comment by fuzhenxin** [comment]
https://mirrors.pku.edu.cn/immortalwrt/
https://mirrors.pku.edu.cn/opnsense/
已增加

**Comment by troubadour-hell** [comment]
感谢~
