### ISSUE TITLE
请求增加 Archlinux CN 仓库

### ISSUE THREAD

**Issue by Firestar-Reimu** [PKUOSC/issues#25]
完整的包信息列表（包名称/架构/维护者/状态）请 [点击这里](https://github.com/archlinuxcn/repo) 查看。

https://www.archlinuxcn.org/archlinux-cn-repo-and-mirror/

官方仓库地址：https://repo.archlinuxcn.org/
镜像地址: https://mirrors.pku.edu.cn/archlinuxcn/

```
archlinuxcn rsync://repo@sync.repo.archlinuxcn.org/repo/ 97.84G
```

**Comment by leavelet** [comment]
收到，我们将于近期处理

**Comment by fuzhenxin** [comment]
https://mirrors.pku.edu.cn/archlinuxcn/  已增加
