### ISSUE TITLE
请求添加Manjaro镜像源

### ISSUE THREAD

**Issue by Firestar-Reimu** [PKUOSC/issues#26]
Manjaro Linux 基于 [Arch Linux](https://zh.wikipedia.org/wiki/Arch_Linux)，但拥有自己独立的软件仓库。Manjaro 的目标是让强大的 Arch 更方便用户使用，Manjaro 使用著名的 [Pacman](https://zh.wikipedia.org/wiki/Pacman) 且可以直接利用 AUR 上的资源。Manjaro 本身使用三个软件仓库：不稳定库，即含有那些不成熟的 Arch 包，这些包与 Arch 源有 1-2 天 的延后；测试库，每周同步一次，包含那些 Arch 不稳定源的包；以及稳定库，包含那些由开发团队确认稳定的软件。

Manjaro镜像的说明都在这里：

https://wiki.manjaro.org/index.php/Manjaro_Mirrors

这是tuna镜像站的manjaro镜像的数据，可供参考

```
manjaro  rsync://mirror.yandex.ru/mirrors/manjaro/  124G
```

**Comment by fuzhenxin** [comment]
镜像站本来是有这个仓库的 https://mirrors.pku.edu.cn/manjaro/

**Comment by Firestar-Reimu** [comment]
OK，那就是没有Manjaro仓库的help（使用指南）

仓库的顺序也不完全按照A-Z顺序（半恼）

**Comment by fuzhenxin** [comment]
欢迎贡献文档，欢迎修改前端
