### ISSUE TITLE
增加龙芯和RISC-V相关仓库

### ISSUE THREAD

**Issue by leavelet** [PKUOSC/issues#29]
仓库说明：龙芯和RISC-V的 Arch和Fedora仓库

同步说明：

都是`rsync`方法。

1. 龙芯架构 Arch Linux：`mirrors.wsyu.edu.cn::loongarch/archlinux/`，命名`Archlinux LoongArch`，建议二级目录称`archlinuxla`
2. 龙芯架构 Fedora：`mirrors.wsyu.edu.cn::fedora`，命名`Fedora LoongArch`，建议二级目录名称`fedorala`
3. RISC-V 架构的Arch Linux: `mirrors.wsyu.edu.cn::archriscv`，命名`Archlinux RISC-V`，建议二级目录名称`archlinuxriscv`

**Comment by fuzhenxin** [comment]
备注：建议控制速度

**Comment by fuzhenxin** [comment]
loongarch archriscv已增加，未见其他镜像站同步fedora，暂不添加。
