### ISSUE TITLE
ubuntu镜像下载为空，死循环

### ISSUE THREAD

**Issue by majiajack** [PKUOSC/issues#34]
https://mirrors.pku.edu.cn/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/
点击 ubuntu 后进不去目录一直这个目录里面跳转

**Comment by fuzhenxin** [comment]
这个是正常的，同步下来之后就会有一个ubuntu的软链接指向这个文件夹自己。https://mirrors.pku.edu.cn/ubuntu/ 这个路径下的其他文件才是镜像库真正存储软件的地方。
