### ISSUE TITLE
增加 Emacs 内建包管理器 package.el 的软件源 ELPA。

### ISSUE THREAD

**Issue by liyan-ah** [PKUOSC/issues#38]
如题。
参见 [清华大学开源软件镜像站](https://mirrors.tuna.tsinghua.edu.cn/)。

作为一款优秀的开源编辑器，Emacs 的生命力凸显韧性。其优秀的兼容性使得很多工作：诸如 Latex 文档编写、Markdown 文档编写、日常工作中的集成环境等都可在 Emacs 里完成。其无愧于“神的编辑器”之称。
 ELPA 作为 Emacs 的软件源，对于其使用有足够的重要性和必要性。建议收录并维护，为国内的 Emacs 道友提供支持。

**Comment by fuzhenxin** [comment]
不好意思，如https://mirrors.pku.edu.cn/Status所示，北大镜像站的存储空间不足，无法满足新镜像了，感谢支持。
