### ISSUE TITLE
No raspbian && debian-security

### ISSUE THREAD

**Issue by AnterCreeper** [PKUOSC/issues#4]
As below:
debian-security which i though is very necessary (
http://mirrors.pku.edu.cn/debian/debian-security buster/updates Release
  404  Not Found [IP: 162.105.120.100 80]

**Comment by fuzhenxin** [comment]
Thanks! They will be online in a week. And I will reply here at that time.

**Comment by JeremyGuo** [comment]
It may work now. in http://mirrors.pku.edu.cn/debian-security/
