### ISSUE TITLE
抱歉，个人觉得还有些必要的包，之前没有考虑完全

### ISSUE THREAD

**Issue by AnterCreeper** [PKUOSC/issues#5]
另外，希望可以进行宣传和推行学校计算中心和实验室进行换源
1.rhel系（如果学校内有需求）
2.latex系，可以直接推广到校内，配合未来的overleaf项目可以满足需求
之前的raspbian是为了可以方便校内使用，当然树莓派的使用越来越多
另外，没有必要像某些镜像站大杂烩，现在的状况挺好

**Comment by AnterCreeper** [comment]
latex包括texlive和texstudio

**Comment by fuzhenxin** [comment]
本站尚未公开，处于测试阶段。公开之后我们会进行一些宣传。
关于latex和rhel系，需要我们调研后再决定。当然，你可以直接贡献同步脚本。
我们欢迎以pull requests的方式添加更多镜像（贡献同步脚本即可）。

**Comment by fuzhenxin** [comment]
另外，我们很尊重各镜像站，不排除成为大杂烩的可能性。

**Comment by JeremyGuo** [comment]
texlive和texstudio(git)都添加了,release之后会加入
