### ISSUE TITLE
首页信息与 json 状态信息不一致

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [PKUOSC/issues#9]
可以注意到，在 https://mirrors.pku.edu.cn/monitor/status 中有 [hugging-face-models 的存在](https://mirrorz.org/list/hugging-face-models)，而在[首页](https://mirrors.pku.edu.cn/Mirrors)中并未显示，这是期待的行为还是相应状态信息并未清理

**Comment by fuzhenxin** [comment]
感谢提醒！系统未删除已下线仓库。已删除。
